import type { BuildingType, CellCoord, GamePhase, GridState, PlacementKind, Race, UnitType } from './primitives';
import type { BattleResult, MatchResult, RoundSummary, SfxEvent, UiMessage } from './events';
import type { BuildingState, DeploymentUnit, UnitState } from './entities';

export interface GameState {
  phase: GamePhase;
  playerRace: Race;
  enemyRace: Race;
  turn: number;
  gold: number;
  rngSeed: number;
  goldDebtNextTurn: number;
  loanUsedThisTurn: boolean;
  enemyGoldDebtNextTurn: number;
  enemyGold: number;
  enemyUnlockedUnits: Record<UnitType, boolean>;
  enemyPlacementSlots: number;
  enemyNextPlacementSlotCost: number;
  maxHp: number;
  playerHp: number;
  enemyHp: number;
  matchResult: MatchResult | null;
  intermissionMsRemaining: number;
  pendingPlayerDamage: number;
  pendingEnemyDamage: number;
  unlockedUnits: Record<UnitType, boolean>;
  unlockedBuildings: Record<BuildingType, boolean>;
  placementSlots: number;
  placementsUsedThisTurn: number;
  nextPlacementSlotCost: number;
  grid: GridState;
  deployments: DeploymentUnit[];
  enemyDeployments: DeploymentUnit[];
  units: UnitState[];
  buildings: BuildingState[];
  nextUnitId: number;
  nextBuildingId: number;
  selectedUnitType: UnitType;
  selectedBuildingType: BuildingType;
  selectedPlacementKind: PlacementKind;
  selectedUnitId: number | null;
  hoveredCell: CellCoord | null;
  message: UiMessage | null;
  sfxEventId: number;
  sfxEvents: SfxEvent[];
  battleTimeMs: number;
  result: BattleResult | null;
  lastRoundSummary: RoundSummary | null;
}
